language: go

go:
    - 1.8

sudo: required
services:
  - docker

before_script:
  - make get-build-deps

script:
  - make check-vendor-licenses
  - make docker-build

install:
  - nvm install node
  - nvm use node
  - node --version
  - npm --version
  - npm install -g elm@0.18.0
