FROM bitnami/minideb:stretch

EXPOSE 8081

COPY tmp/build/linux-amd64/metadata /prototype/
COPY ./swagger-ui/ /prototype/swagger-ui/

COPY ui/search.html /prototype/assets/index.html
COPY ui/search.js /prototype/assets/
COPY ui/static /prototype/assets/static/

ENV SWAGGER_UI_PATH=/prototype/swagger-ui/
ENV ASSETS_PATH=/prototype/assets/


ENTRYPOINT [ "/prototype/metadata", "server"]
